### ISSUE TITLE
Relational Data

### ISSUE THREAD

**Issue by kbaba1001** [kbaba1001/sowing#2]
単に Relational Data を作ると言うより、特定のカラムに対して lambda などで処理を実行できるようにしたほうが使い勝手良さそう。

例えば、

book.yml:

```yaml
item1:
  name: 'Refactoring: Improving the Design of Existing Code'
  author: 'Martin Fowler'
  user_id: 1
item2:
  name: 'Webを支える技術'
  author: '山本 陽平'
  user_id: 2
```

```ruby
runner.create(Book, rules: {
    user_id: -> (id) {
      User.find(id)
    },
    author: -> (value) {
      value.camelize
    }
  }
)
```

みたいな感じ。 `rules` は key がカラム名 value が lambda。
lambda の引数には各データの値が入る。
